// ============================================
// build-static.js
// Produce an encrypted, read-only static site in docs/ for GitHub Pages.
//
//   node build-static.js
//
// Password source (first match wins):
//   1. FLIGHT_PW environment variable
//   2. .viewer-password file (gitignored) — put your shared password there
//
// Output (all committed & pushed):
//   docs/index.html, style.css, app.js, config.js (APP_MODE='static')
//   docs/data/<slug>/<year>-<month>.json  AES-GCM encrypted { stats, results }
//   docs/data/manifest.json                plaintext list of routes & months
//   docs/.nojekyll
// ============================================

const fs = require('fs');
const path = require('path');
const { webcrypto } = require('crypto');
const cache = require('./cache');

const { subtle } = webcrypto;
const ROOT = __dirname;
const CACHE_DIR = path.join(ROOT, 'cache');
const PUBLIC_DIR = path.join(ROOT, 'public');
const DOCS_DIR = path.join(ROOT, 'docs');
const DATA_DIR = path.join(DOCS_DIR, 'data');
const PBKDF2_ITERATIONS = 150000;

// --- password ---
function getPassword() {
  if (process.env.FLIGHT_PW) return process.env.FLIGHT_PW.trim();
  const pwFile = path.join(ROOT, '.viewer-password');
  if (fs.existsSync(pwFile)) {
    const pw = fs.readFileSync(pwFile, 'utf8').trim();
    if (pw) return pw;
  }
  console.error('❌ 找不到密碼。請建立 .viewer-password 檔（放入分享密碼）或設定 FLIGHT_PW 環境變數。');
  process.exit(1);
}

// --- AES-GCM encryption (mirrors decryptPayload() in public/app.js) ---
async function deriveKey(password, salt) {
  const km = await subtle.importKey(
    'raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']);
  return subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: PBKDF2_ITERATIONS, hash: 'SHA-256' },
    km, { name: 'AES-GCM', length: 256 }, false, ['encrypt']);
}

async function encryptObj(obj, password) {
  const salt = webcrypto.getRandomValues(new Uint8Array(16));
  const iv = webcrypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(password, salt);
  const ct = await subtle.encrypt(
    { name: 'AES-GCM', iv }, key, new TextEncoder().encode(JSON.stringify(obj)));
  return {
    v: 1,
    salt: Buffer.from(salt).toString('base64'),
    iv: Buffer.from(iv).toString('base64'),
    ct: Buffer.from(new Uint8Array(ct)).toString('base64'),
  };
}

// --- stats (mirrors GET /api/stats in server.js) ---
function computeStats(allData) {
  const allFlights = Object.values(allData).flat();
  const total = allFlights.length;
  const withPrices = allFlights.filter(f => f.price !== null);
  const cheapest = withPrices.length > 0
    ? withPrices.reduce((a, b) => (a.price < b.price ? a : b))
    : null;
  return {
    totalSearches: total,
    withPrices: withPrices.length,
    noPrices: total - withPrices.length,
    cheapest: cheapest
      ? { date: cheapest.date, returnDate: cheapest.returnDate, price: cheapest.price }
      : null,
    dates: Object.keys(allData).sort(),
  };
}

async function main() {
  const password = getPassword();

  // Wipe docs/ so stray/internal files never leak to the public site
  fs.rmSync(DOCS_DIR, { recursive: true, force: true });
  fs.mkdirSync(DATA_DIR, { recursive: true });

  // 1. Copy front-end assets (config.js is overwritten to static below)
  for (const f of ['index.html', 'style.css', 'app.js']) {
    fs.copyFileSync(path.join(PUBLIC_DIR, f), path.join(DOCS_DIR, f));
  }
  fs.writeFileSync(path.join(DOCS_DIR, 'config.js'),
    "// Generated by build-static.js — served from GitHub Pages\nwindow.APP_MODE = 'static';\n", 'utf8');
  fs.writeFileSync(path.join(DOCS_DIR, '.nojekyll'), '', 'utf8');

  // 2. Encrypt each route × month that has data → docs/data/<slug>/<year>-<month>.json
  const manifestRoutes = [];
  for (const { slug, label, months } of cache.listRoutes()) {
    const slugDir = path.join(DATA_DIR, slug);
    fs.mkdirSync(slugDir, { recursive: true });
    const manifestMonths = [];

    for (const { year, month } of months) {
      const flights = cache.getAll(slug, year, month);
      if (Object.keys(flights).length === 0) continue;

      const lastUpdated = cache.getLastUpdated(slug, year, month);
      const payload = {
        stats: { ...computeStats(flights), lastUpdated },
        results: { flights, lastUpdated },
      };
      const encrypted = await encryptObj(payload, password);
      const fileKey = `${year}-${month}`; // unpadded month → matches app.js getSearchParams()
      fs.writeFileSync(path.join(slugDir, `${fileKey}.json`), JSON.stringify(encrypted), 'utf8');

      manifestMonths.push({ year, month, label: `${year}年${month}月`, count: payload.stats.totalSearches });
      console.log(`  🔒 ${label}  ${fileKey}  (${payload.stats.totalSearches} 筆, ${payload.stats.withPrices} 有價格)`);
    }

    if (manifestMonths.length) {
      manifestRoutes.push({ slug, label, months: manifestMonths });
    }
  }

  // 3. Plaintext manifest (routes & months only — no prices, safe to expose)
  fs.writeFileSync(path.join(DATA_DIR, 'manifest.json'),
    JSON.stringify({ routes: manifestRoutes, generatedAt: new Date().toISOString() }, null, 2), 'utf8');

  const totalMonths = manifestRoutes.reduce((n, r) => n + r.months.length, 0);
  console.log(`\n✅ 靜態網站已產生於 docs/（${manifestRoutes.length} 條航線 / ${totalMonths} 個月份，已加密）`);
  console.log('   下一步：git add docs && git commit && git push  → GitHub Pages 自動更新');
}

main().catch(err => { console.error('❌ build 失敗:', err); process.exit(1); });
